import type { Campaign } from "./types"

export const mockCampaigns: Campaign[] = [
  {
    id: "campaign-1",
    name: "Summer Sizzle Sale",
    submittedBy: "Alice Johnson",
    submissionDate: new Date("2024-06-25"),
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    tags: ["Age:18-24", "Age:25-34", "Gender:Any"],
    targetingNotes: "Prioritize locations near beaches and public pools.",
    status: "approved",
    creatives: [
      {
        id: "file-1",
        file: new File([""], "summer-promo.mp4", { type: "video/mp4" }),
        name: "Summer Promo Video",
        notes: "Main 30s spot for the campaign.",
        status: "success",
        proofOfPlay: true,
        approvalStatus: "approved",
        preview: "/placeholder.svg?height=100&width=160",
        width: 1920,
        height: 1080,
        duration: 30,
      },
    ],
  },
  {
    id: "campaign-2",
    name: "Back to School Bonanza",
    submittedBy: "Bob Williams",
    submissionDate: new Date("2024-08-01"),
    startDate: new Date("2024-08-15"),
    endDate: new Date("2024-09-15"),
    tags: ["Age:18-24"],
    targetingNotes: "Focus on screens near college campuses and shopping malls.",
    status: "waiting for approval",
    creatives: [
      {
        id: "file-2",
        file: new File([""], "school-banner.jpg", { type: "image/jpeg" }),
        name: "School Supplies Banner",
        notes: "Static image for digital billboards.",
        status: "success",
        proofOfPlay: false,
        approvalStatus: "pending",
        preview: "/placeholder.svg?height=100&width=160",
        width: 1200,
        height: 628,
      },
      {
        id: "file-3",
        file: new File([""], "dorm-deals.png", { type: "image/png" }),
        name: "Dorm Deals",
        notes: "Special offer for college students.",
        status: "success",
        proofOfPlay: false,
        approvalStatus: "pending",
        preview: "/placeholder.svg?height=100&width=160",
        width: 1080,
        height: 1080,
      },
    ],
  },
  {
    id: "campaign-4",
    name: "Autumn Harvest Festival",
    submittedBy: "Charlie Brown",
    submissionDate: new Date("2024-08-10"),
    startDate: new Date("2024-09-20"),
    endDate: new Date("2024-10-20"),
    tags: ["Age:25-34", "Age:35-44"],
    targetingNotes: "Target farmers markets and community centers.",
    status: "waiting for approval",
    creatives: [
      {
        id: "file-4",
        file: new File([""], "autumn-ad.mp4", { type: "video/mp4" }),
        name: "Harvest Fest Ad",
        notes: "15s video spot.",
        status: "success",
        proofOfPlay: false,
        approvalStatus: "approved",
        preview: "/placeholder.svg?height=100&width=160",
        width: 1920,
        height: 1080,
        duration: 15,
      },
      {
        id: "file-5",
        file: new File([""], "autumn-flyer.jpg", { type: "image/jpeg" }),
        name: "Harvest Fest Flyer",
        notes: "Static image for social media.",
        status: "success",
        proofOfPlay: false,
        approvalStatus: "rejected",
        preview: "/placeholder.svg?height=100&width=160",
        width: 1080,
        height: 1080,
      },
    ],
  },
  {
    id: "campaign-3",
    name: "Winter Wonderland",
    submittedBy: "Alice Johnson",
    submissionDate: new Date("2024-11-15"),
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    tags: ["Age:35-44", "Gender:Female"],
    targetingNotes: "Rejected due to budget constraints.",
    status: "rejected",
    creatives: [],
  },
]
